### ISSUE TITLE
panic in transform.go when it's trying to reslice 

### ISSUE THREAD

**Issue by diptomondal007** [lithammer/fuzzysearch#61]
It seems it's trying to reslice with invalid index in `v1.1.5`
```
panic: runtime error: slice bounds out of range [5:3]

goroutine 399472 [running]:
golang.org/x/text/transform.String({0xe4c3d0, 0x13ce5c0}, {0xc00042d358, 0x3})
	/vendor/golang.org/x/text/transform/transform.go:650 +0xbe5
github.com/lithammer/fuzzysearch/fuzzy.stringTransform({0xc00042d358, 0x3}, {0xe4c3d0?, 0x13ce5c0?})
	/vendor/github.com/lithammer/fuzzysearch/fuzzy/fuzzy.go:243 +0x5a
github.com/lithammer/fuzzysearch/fuzzy.match({0xc00042d358?, 0x44fe72?}, {0xc0007a1950, 0x13}, {0xe4c3d0, 0x13ce5c0})
```

**Comment by diptomondal007** [comment]
yes true actually I upgraded the version but tried with old docker image and thought not working. thanks
